---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-1-serviceaccount
  namespace: gitlab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-1-serviceaccount-role
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - nodes
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-1-serviceaccount-rule
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-1-serviceaccount-role
subjects:
  - kind: ServiceAccount
    name: gitlab-1-serviceaccount
    namespace: gitlab
